### ISSUE TITLE
[BUG] Set Default organization empty

### ISSUE THREAD

**Issue by weisgerberm** [netresearch/t3x-cowriter#3]
Currently it adds the default organization 0 instead of an empty value. The API rejects the call if a 0 is sent.

Replace this in [ext_conf_template.txt](https://github.com/netresearch/t3-cowriter/blob/main/ext_conf_template.txt)
openaiOrg = 0
to
openaiOrg =

**Comment by Gitsko** [comment]
Thanks for the note, we have added the change in the current main branch.
