### ISSUE TITLE
Plugin only visible on FCE "Text"

### ISSUE THREAD

**Issue by vergissberlin** [netresearch/t3x-cowriter#4]
**Describe the bug**
Hi! After installation on a fresh TYPO3 11.5.22 the CKEditor Plugin is only available on FCE "Text" and not on other FCE with real text editor.

**To Reproduce**
1. Go to Page Module
2. Click on Add _Text Image_ FCE
3. Check if plugin is available

**Expected behavior**
Please add this to other FCE too!

**Screenshots**
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/179964/217031193-f5300603-2aeb-4418-81ab-8be6c196d345.png">

**Comment by Gitsko** [comment]
In Release v1.2.0 all standard TYPO3 content elements should work.
