### ISSUE TITLE
CKEditor style is greyed out

### ISSUE THREAD

**Issue by netthinks** [netresearch/t3x-cowriter#5]
After installing t3_cowriter, the style button in CKEditor is greyed out, nothing is selectable. Deinstalling t3_cowriter enables the styles again...

TYPO3 11.5.24

![grafik](https://user-images.githubusercontent.com/23073131/219667777-01440c0d-edd6-414b-9816-ae5970f57505.png)

**Comment by Gitsko** [comment]
Hi @netthinks, 
thank you for the hint, we have now in the Release v1.2.1 the RTE stand configuration of TYPO3 with load, so the styles should be available again.

If it does not work, please open the issue again

Have Fun!
