### ISSUE TITLE
Overwrites existing RTE config

### ISSUE THREAD

**Issue by olagwin** [netresearch/t3x-cowriter#8]
**Describe the bug**
I had a system with the bootstrap extension (but should happen in all systems with existing config) and there it overwrites my existing rte config, so that I couldn't use defined classes or text alignment anymore.

I would expect, that I add the cowriter button manually in my rte config and some documentation for that. Using the shipped rte config of the cowriter extension should be optional.

**Comment by Gitsko** [comment]
In Version 1.2.0 the TSConfig is no longer loaded automatically in case an own RTEConfig is available, e.g. from the bootstrap extension.

The TSConfig can be added manually if needed. The documentation was supplemented in this regard.
