### ISSUE TITLE
Get current version of ckeditor plugin automaticly

### ISSUE THREAD

**Issue by olagwin** [netresearch/t3x-cowriter#9]
**Is your feature request related to a problem? Please describe.**
New versions of https://github.com/netresearch/ckeditor-cowriter don't go automaticly into this extension and have to be added manually.

**Describe the solution you'd like**
No manual update of ckeditor plugin behind is necessary anymore.

**Comment by Gitsko** [comment]
Hi @ngolatka,
can you solve this with a github action ? 

The goal is that the files in the `dist` folder (from npm https://www.npmjs.com/package/@netresearch/ckeditor-cowriter?activeTab=code) is automatically committed in the main branch or a merge request in this repo.

**Comment by ngolatka** [comment]
@Gitsko 
To check how this can be done, can you please tell me which are source folders/files in this repo https://github.com/netresearch/ckeditor-cowriter ?

And what's the target directory here https://github.com/netresearch/t3-cowriter ?

Or are some files only created during a build?

**Comment by ngolatka** [comment]
@Gitsko and @olagwin 
After some playing around with this, I think it is technically possible to do this.

But investigating and setting everything up would take a lot more time than this feature would save. If new releases of https://github.com/netresearch/ckeditor-cowriter only happen once every few weeks, and copying the necessary stuff by hand takes a few minutes, then the effort does not justify the result.

I suggest we leave the process as it is.

**Comment by olagwin** [comment]
We talked about it and agree with this view. The plugin is rather small and it seems there won't be much need for adjustments in the future, at least not more than once a month in average.
